### ISSUE TITLE
The "constant ::Fixnum is deprecated" warning in Ruby 2.4

### ISSUE THREAD

**Issue by kapso** [sibevin/random_token#6]
Seeing this warning in Ruby 2.4 --

/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/random_token-1.1.0/lib/random_token.rb:176: warning: constant ::Fixnum is deprecated

**Comment by sibevin** [comment]
@kapso 

First, thank you for this issue report, I will fix it ASAP. On the other hand, I will change this issue title to make it clearer and easy to find if other users have the same issue.

Actually, I am not so "active" on this project, but If there are reported issues or bugs, I would try to fix them. BTW, any pull requests are welcome.

**Comment by sibevin** [comment]
Fixed on v1.1.1

**Comment by kapso** [comment]
@sibevin thanks a lot for the quick fix.
